---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-wazi
    kind: solution
    catalog_id: 05308d56-42c7-4763-ab3c-f2da0a788024
    offering_id: d86488e7-cb66-438e-a30f-63d9bad35cc2
    variations:
      - name: quickstart
        mark_ready: false
        install_type: fullstack
      - name: standard
        mark_ready: false
        install_type: fullstack
